spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exercisesdb
    username: root
    password: rootpassword
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
